/**
 * Declare action types for reducers
 */
export const REQUEST_CHUCK_NORRIS_RANDOM_JOKE = 'REQUEST_CHUCK_NORRIS_RANDOM_JOKE';
export const CHUCK_NORRIS_RANDOM_JOKE_LOADING = 'CHUCK_NORRIS_RANDOM_JOKE_LOADING';
export const CHUCK_NORRIS_RANDOM_JOKE_FAILED = 'CHUCK_NORRIS_RANDOM_JOKE_FAILED';
export const ADD_CHUCK_NORRIS_RANDOM_JOKE = 'ADD_CHUCK_NORRIS_RANDOM_JOKE';
export const CHUCK_NORRIS_RANDOM_JOKE_REQUEST_SUCCESS = 'CHUCK_NORRIS_RANDOM_JOKE_REQUEST_SUCCESS';

export const REQUEST_FAVORITE_JOKES = 'REQUEST_FAVORITE_JOKES';
export const FAVORITE_JOKES_LOADING = 'FAVORITE_JOKES_LOADING';
export const FAVORITE_JOKES_FAILED = 'FAVORITE_JOKES_FAILED';
export const ADD_FAVORITE_JOKES = 'ADD_FAVORITE_JOKES';
export const FAVORITE_JOKES_REQUEST_SUCCESS = 'FAVORITE_JOKES_REQUEST_SUCCESS';
